language: node_js

node_js:
- "8.9.1"

before_install:
- npm i -g npm@6.9.0

script:
- npm run test:coverage
- npm run build

deploy:
	providers: pages
	skip_cleanup: true
	github_token: $github_token
	local_dir: build
	on:
		branch: master
